/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mynilai_22030003;

/**
 *
 * @author 62857
 */
public class mynilai extends javax.swing.JFrame {

    /**
     * Creates new form mynilai
     */
    public mynilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInMahasiswa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pMatkul = new javax.swing.JLabel();
        MatkulCb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        iNMahasiswa = new javax.swing.JLabel();
        iNIM = new javax.swing.JLabel();
        iNama = new javax.swing.JLabel();
        iJhadir = new javax.swing.JLabel();
        iNtugas = new javax.swing.JLabel();
        iNuts = new javax.swing.JLabel();
        iNuas = new javax.swing.JLabel();
        Onim = new javax.swing.JTextField();
        Onama = new javax.swing.JTextField();
        OJhadir = new javax.swing.JTextField();
        OiNtugas = new javax.swing.JTextField();
        OiNuts = new javax.swing.JTextField();
        OiNuas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        nAmahasiswa = new javax.swing.JLabel();
        Hmatkul = new javax.swing.JLabel();
        jNIM = new javax.swing.JLabel();
        jNama = new javax.swing.JLabel();
        jNilaiAkhir = new javax.swing.JLabel();
        jGradeNilai = new javax.swing.JLabel();
        Hnim = new javax.swing.JTextField();
        Hnama = new javax.swing.JTextField();
        HniAkhir = new javax.swing.JTextField();
        HgNilai = new javax.swing.JTextField();
        jHitung = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jTutupApk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pInMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pInMahasiswa.setForeground(new java.awt.Color(51, 0, 204));
        pInMahasiswa.setText("PROSES INPUT NILAI MAHASISWA");

        pMatkul.setText("Pilih Matakuliah");

        MatkulCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aljabar Linear", "Kewirausahaan", "Grafika Komputer", "Dasar Animasi3D" }));
        MatkulCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatkulCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pMatkul)
                .addGap(51, 51, 51)
                .addComponent(MatkulCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pMatkul)
                    .addComponent(MatkulCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iNMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iNMahasiswa.setText("Input Nilai Mahasiswa");

        iNIM.setText("Input NIM");

        iNama.setText("Input Nama");

        iJhadir.setText("Input Jum Presensi Kehadiran");

        iNtugas.setText("Input Nilai Tugas");

        iNuts.setText("Input Nilai UTS");

        iNuas.setText("Input Nilai UAS");

        Onim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iNMahasiswa)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iNIM)
                            .addComponent(iNama)
                            .addComponent(iJhadir)
                            .addComponent(iNtugas)
                            .addComponent(iNuts)
                            .addComponent(iNuas))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OiNuas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OiNuts, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OiNtugas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OJhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Onim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Onama, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iNMahasiswa)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNIM)
                    .addComponent(Onim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNama)
                    .addComponent(Onama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iJhadir)
                    .addComponent(OJhadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNtugas)
                    .addComponent(OiNtugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNuts)
                    .addComponent(OiNuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNuas)
                    .addComponent(OiNuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        nAmahasiswa.setText("Nilai Akhir Mahasiswa");

        Hmatkul.setText("Menampilkan Nama Matakuliah yang sudah dipilih");

        jNIM.setText("NIM                   :");

        jNama.setText("Nama                 :");

        jNilaiAkhir.setText("Nilai Akhir           :");

        jGradeNilai.setText("Grade Nilai          :");

        Hnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HnimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNama))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Hnim, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Hnama)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(nAmahasiswa))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Hmatkul))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jGradeNilai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jNilaiAkhir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HgNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(HniAkhir))))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nAmahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hmatkul)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNIM)
                    .addComponent(Hnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNama)
                    .addComponent(Hnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNilaiAkhir)
                    .addComponent(HniAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGradeNilai)
                    .addComponent(HgNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jHitung.setText("Hitung");
        jHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHitungActionPerformed(evt);
            }
        });

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jTutupApk.setText("Tutup Aplikasi");
        jTutupApk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTutupApkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(pInMahasiswa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHitung)
                                .addGap(18, 18, 18)
                                .addComponent(jReset)
                                .addGap(18, 18, 18)
                                .addComponent(jTutupApk)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHitung)
                            .addComponent(jReset)
                            .addComponent(jTutupApk))))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatkulCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatkulCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatkulCbActionPerformed

    private void OnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OnimActionPerformed

    private void HnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HnimActionPerformed

    private void jHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHitungActionPerformed
        // TODO add your handling code here:
        int iJhadir = Integer.parseInt(OJhadir.getText());
        int iNtugas = Integer.parseInt(OiNtugas.getText());
        int iNuts = Integer.parseInt(OiNuts.getText());
        int iNuas = Integer.parseInt(OiNuas.getText());
        String grade;
        
        double jNilaiAkhir = (0.2 * iJhadir) + (0.2 * iNtugas) + (0.3 * iNuts) + (0.3 * iNuas);
        
        if (jNilaiAkhir >= 80) {
            grade = "A";
        }else if (jNilaiAkhir >= 65 && jNilaiAkhir <= 79.9) {
            grade = "B";
        }else if (jNilaiAkhir >= 55 && jNilaiAkhir <= 64.9) {
            grade = "C";
        }else if (jNilaiAkhir >= 40 && jNilaiAkhir <= 54.9) {
            grade = "D";
        }else {
            grade = "E";
        }
        
        String nilaiAkhirStr = String.valueOf(jNilaiAkhir);
        
        Hmatkul.setText(MatkulCb.getSelectedItem().toString());
        Hnim.setText(Onim.getText());
        Hnama.setText(Onama.getText());
        HniAkhir.setText(nilaiAkhirStr);
        HgNilai.setText(grade);
        
        
        
        
    }//GEN-LAST:event_jHitungActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        // TODO add your handling code here:
        Onim.setText("");
        Onama.setText("");
        OJhadir.setText("");
        OiNtugas.setText("");
        OiNuts.setText("");
        OiNuas.setText("");
        Hmatkul.setText("");
        Hnim.setText("");
        Hnama.setText("");
        HniAkhir.setText("");
        HgNilai.setText("");
    }//GEN-LAST:event_jResetActionPerformed

    private void jTutupApkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTutupApkActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jTutupApkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mynilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HgNilai;
    private javax.swing.JLabel Hmatkul;
    private javax.swing.JTextField Hnama;
    private javax.swing.JTextField HniAkhir;
    private javax.swing.JTextField Hnim;
    private javax.swing.JComboBox<String> MatkulCb;
    private javax.swing.JTextField OJhadir;
    private javax.swing.JTextField OiNtugas;
    private javax.swing.JTextField OiNuas;
    private javax.swing.JTextField OiNuts;
    private javax.swing.JTextField Onama;
    private javax.swing.JTextField Onim;
    private javax.swing.JLabel iJhadir;
    private javax.swing.JLabel iNIM;
    private javax.swing.JLabel iNMahasiswa;
    private javax.swing.JLabel iNama;
    private javax.swing.JLabel iNtugas;
    private javax.swing.JLabel iNuas;
    private javax.swing.JLabel iNuts;
    private javax.swing.JLabel jGradeNilai;
    private javax.swing.JButton jHitung;
    private javax.swing.JLabel jNIM;
    private javax.swing.JLabel jNama;
    private javax.swing.JLabel jNilaiAkhir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jReset;
    private javax.swing.JButton jTutupApk;
    private javax.swing.JLabel nAmahasiswa;
    private javax.swing.JLabel pInMahasiswa;
    private javax.swing.JLabel pMatkul;
    // End of variables declaration//GEN-END:variables
}
